import { listAnswers, listQuestions } from '../../services/questionApi.js';
import { emptyState, escapeText } from '../Navigation.js';
export async function QuestionsPage(_user, query = '') {
  const questions = (await listQuestions()).filter(question => `${question.title} ${question.subject || ''} ${question.description || ''}`.toLowerCase().includes(query.toLowerCase()));
  const body = questions.length
    ? (await Promise.all(questions.map(async question => ({
      question,
      answers: await listAnswers(question.id)
    })))).map(({ question, answers }) => `<article class="question-card"><div class="question-row"><div class="question-avatar">${escapeText((question.authorName || '?')[0])}</div><div class="question-main"><h3>${escapeText(question.title)}</h3><div>${question.subject ? `<span class="tag">${escapeText(question.subject)}</span>` : ''}</div><p class="question-meta">Asked by ${escapeText(question.authorName || 'a learner')} · ${new Date(question.createdAt).toLocaleDateString()}</p><p class="question-meta">${answers.length} ${answers.length === 1 ? 'answer' : 'answers'}</p></div><div class="vote-box"><button data-vote="${escapeText(question.id)}" aria-label="Upvote">⌃</button><span>${question.votes || 0}</span></div></div><div class="answers-list">${answers.map(answer => `<article class="answer-row"><strong>${escapeText(answer.authorName || 'Learner')}</strong><p>${escapeText(answer.body)}</p></article>`).join('') || '<p class="settings-hint">No answers yet. Share a helpful response.</p>'}<form class="question-answer-form" data-question-id="${escapeText(question.id)}"><label for="answer-${escapeText(question.id)}">Your answer</label><textarea class="field" id="answer-${escapeText(question.id)}" name="body" required maxlength="3000" rows="2" placeholder="Share an explanation or helpful suggestion"></textarea><button class="btn btn-sm" type="submit">Post answer</button></form></div></article>`).join('')
    : emptyState(query ? 'No questions found' : 'No questions have been posted', query ? 'Try a different search.' : 'Ask the first question and let the community grow around it.', '<button class="btn btn-sm" data-modal="question">＋ Ask the first question</button>');
  return `<div class="welcome-row"><div><h1>Questions & Answers</h1><p>Ask for help, share what you know, and learn together.</p></div><button class="btn btn-sm" data-modal="question">＋ Ask a Question</button></div><div class="content-toolbar"><div class="content-search"><input id="page-search" placeholder="Search questions" value="${escapeText(query)}"></div></div><section class="panel"><div class="panel-head"><h2>Community questions</h2><span class="view-all">${questions.length} ${questions.length === 1 ? 'question' : 'questions'}</span></div>${body}</section>`;
}
